---
- hosts: all
  sudo: yes
  vars: 
    env_paths:
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: ensure unzip is at the latest version
      apt: pkg=unzip state=latest

    - name: Update .bashrc with paths
      template: src=templates/bashrc.j2 dest=/home/vagrant/.bashrc owner=vagrant mode=0644

    - name: ensure vim is at the latest version
      apt: pkg=vim state=latest

    - name: ensure git is at the latest version
      apt: pkg=git state=latest

  handlers:
